Repository parse-community/parse-server-push-adapter, pull requests merged in 2019-07, with the labels that each got.

#128 Add support for apns-priority key
  spec/APNS.spec.js
  src/APNS.js
Labels: enhancement

#127 Add support for apns-push-type
  package-lock.json
  package.json
  spec/APNS.spec.js
  src/APNS.js
Labels: GH Review: needs-revision, enhancement

#138 3.0.6
  .npmignore
  CHANGELOG.md
  package-lock.json
  package.json
Labels: release
